### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Smons** [Saafke/EDSR_Tensorflow#13]
It doesn't work for me with Python 3.9 on macOS.

First, the following packages are required:
    • pillow
    • scikit-image
    • tensorflow-transform
but even with that, I get the error _'ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'_

**Comment by wm19999** [comment]
You need to downgrade your tensorflow version

**Comment by hktalent** [comment]
me too, now work
``` 
$ ls -lah models 
total 225776
drwxr-xr-x   5 51pwn  staff   160B  5 27 11:11 .
drwxr-xr-x  15 51pwn  staff   480B  5 28 20:55 ..
-rw-r--r--   1 51pwn  staff    37M  5 27 11:11 EDSR_x2.pb
-rw-r--r--   1 51pwn  staff    37M  5 27 11:11 EDSR_x3.pb
-rw-r--r--   1 51pwn  staff    37M  5 27 11:11 EDSR_x4.pb
```

python main.py --upscale  --scale 4 --image /Users/51pwn/Downloads/IMG_2315.jpg
```
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/EDSR_Tensorflow/main.py", line 3, in <module>
    import run
  File "/Users/51pwn/MyWork/EDSR_Tensorflow/run.py", line 7, in <module>
    from skimage import io
  File "/Users/51pwn/anaconda3/envs/51pwn4ai/lib/python3.9/site-packages/skimage/__init__.py", line 122, in <module>
    from ._shared import geometry
  File "geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```


```
$ pip list|grep -E "tensorflow|numpy|skimage"
numpy                          1.19.5
tensorflow                     2.5.0
tensorflow-estimator           2.5.0
tensorflow-io-gcs-filesystem   0.32.0
$ python -V
Python 3.9.16

```
